version: "3.2"
services:
  db:
    build:
      context: ./
      dockerfile: Dockerfile-database
    restart: on-failure
    volumes:
      - ./couchdb-data:/opt/couchdb/data
    ports:
      - 5984:5984
